<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [4]:
import numpy as np
array1al9 = [0,1,2,3,4,5,6,7,8,9]
array1al9

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [5]:
np.reshape(array1al9, (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [25]:
ej3 = np.array([0, 2, 0, 3, 0, 4, 0])
ind = np.where(ej3!=0)
ind

(array([1, 3, 5]),)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [28]:
array0y1 = np.random.randint(0,2, (3,3))
array0y1

array([[1, 0, 0],
       [0, 1, 0],
       [1, 1, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [35]:
array_aleatorio = np.random.randint(0, 500, 10)
print(f'Nues tro aray: {array_aleatorio}')
max = np.max(array_aleatorio)
min = np.min(array_aleatorio)
print(f'El máximo es: {max}')
print(f'El minimo es: {min}')

Nues tro aray: [475 257 419 410 339  11 400 114 209 176]
El máximo es: 475
El minimo es: 11


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [41]:
ej6 = np.random.randint(0,10,3)
print(f'El vestor es: {ej6}')
tr = ej6[::-1]
print(f'El vector traspuesto es: {tr}')

El vestor es: [6 2 4]
El vector traspuesto es: [4 2 6]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [67]:
array_tri = np.random.randint(1, 25, (2,3,4))
print(array_tri)

try:
    print(array_tri[array_tri==15][0])
except:
    print("No hay ningún 15 en el array")

[[[15  3  3  1]
  [11 13 20  1]
  [ 6 16 21  1]]

 [[18 24  8 20]
  [15  1 10 21]
  [ 7 13 15 13]]]
15


In [71]:
print(array_tri[0,0,:]) #primera fila
print(array_tri[-1,-1,:]) #última fila

[15  3  3  1]
[ 7 13 15 13]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [78]:
array_ej7 = np.random.randint(1,31,(3,2,5))
print(array_ej7)
print("\nLos dos primeros elementos de cada fila del primer array:")
print(f'{array_ej7[0,:, :2]}')
print("\nTodas las filas de los dos últimos arrays:")
print(f'{array_ej7[1:,:]}')

[[[ 3  4 24  7 16]
  [10 22  3  8 17]]

 [[24 28 29 14 11]
  [30  2 29  4 21]]

 [[23 12  7 10 22]
  [ 1 26 28 16 21]]]

Los dos primeros elementos de cada fila del primer array:
[[ 3  4]
 [10 22]]

Todas las filas de los dos últimos arrays:
[[[24 28 29 14 11]
  [30  2 29  4 21]]

 [[23 12  7 10 22]
  [ 1 26 28 16 21]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [79]:
array_ej8 = np.random.randint(1,25,(4,3,2))
print(array_ej8)

[[[ 9  6]
  [ 5 11]
  [12 22]]

 [[ 3  7]
  [16  3]
  [18 19]]

 [[ 7  8]
  [18  8]
  [17 20]]

 [[ 7 20]
  [ 4  2]
  [22 24]]]


In [82]:
array_ej8[1,1]=0
array_ej8[-1]=-1
array_ej8

array([[[ 9,  6],
        [ 5, 11],
        [12, 22]],

       [[ 3,  7],
        [ 0,  0],
        [18, 19]],

       [[ 7,  8],
        [18,  8],
        [17, 20]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int32)


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [90]:
array_ej9 = np.random.randint(-10, 13,(2,4,3))
print(array_ej9)
elem_mayor_5 = array_ej9[array_ej9>5]

print(f'Elementos mayores a 5: {elem_mayor_5}')

array_ej9[array_ej9<0]=0
print(f'\n{array_ej9}')

[[[ 11 -10  -9]
  [ -2   6  -5]
  [ -3   7 -10]
  [  0  10   6]]

 [[ -2   9  -8]
  [ -2   0   3]
  [  8  -8   9]
  [ 11  12   7]]]
Elementos mayores a 5: [11  6  7 10  6  9  8  9 11 12  7]

[[[11  0  0]
  [ 0  6  0]
  [ 0  7  0]
  [ 0 10  6]]

 [[ 0  9  0]
  [ 0  0  3]
  [ 8  0  9]
  [11 12  7]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [99]:
array_ej10 = np.random.randint(1,28,(3,3,3))
print(array_ej10)

print("\n Subarray del segundo array que contenga solo las dos primeras columnas")
print(array_ej10[1, :, :2])

array_aux = array_ej10[2]
print("\nElementos del tercer array que sean mayores que 20:")
elem = array_aux[array_aux>20]
print(elem)

[[[16 26  6]
  [14 23 12]
  [ 4 17  7]]

 [[27  4 14]
  [27 23  4]
  [22  6 14]]

 [[11 25 19]
  [11 23  7]
  [19  7 23]]]

 Subarray del segundo array que contenga solo las dos primeras columnas
[[27  4]
 [27 23]
 [22  6]]

Elementos del tercer array que sean mayores que 20:
[25 23 23]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [109]:
array_ej11 = np.random.randint(1,21, 10)
print(array_ej11)

max=np.max(array_ej11)
min=np.min(array_ej11)
print(f'Máximo: {max}')
print(f'Mínimo: {min}')

array_ej11[array_ej11==max]=0
array_ej11[array_ej11==min]=0
print(array_ej11)

[12 17  8 20 17 19  2 20  8  7]
Máximo: 20
Mínimo: 2
[12 17  8  0 17 19  0  0  8  7]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [114]:
array_ej12 = np.random.randint(1,101, 15)
print(f'Original:{array_ej12}')
print(f'Ordenado: {np.sort(array_ej12)}')

Original:[ 70  63  65  66  22  73  71  28  77  19  65  52 100  63  61]
Ordenado: [ 19  22  28  52  61  63  63  65  65  66  70  71  73  77 100]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [119]:
array_ej11_2 = np.random.randint(1,10,(4,4))
print(array_ej11_2)
suma_columnas = np.sum(array_ej11_2, axis =0)
suma_filas = np.sum(array_ej11_2, axis =1)
print(f'La suma de las columnas es : {suma_columnas}')
print(f'La suma de las filas es : {suma_filas}')

[[5 9 4 1]
 [4 4 5 7]
 [4 1 6 8]
 [9 1 7 1]]
La suma de las columnas es : [22 15 22 17]
La suma de las filas es : [19 20 19 18]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [132]:
array_12 = np.zeros((5,5), dtype=int)
array_12[0]=1
array_12[-1]=1
array_12[:,0]=1
array_12[:,-1]=1
array_12

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [140]:
array_ej13 = np.random.randint(1,100,10000)
print(array_ej13)

mean = np.mean(array_ej13)
std = np.std(array_ej13)
print(f'La media de mi array es: {mean}')
print(f'La desviación típica de mi array es: {round(std,2)}')


[70 19 12 ... 70 30 46]
La media de mi array es: 50.0202
La desviación típica de mi array es: 28.69


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [143]:
array_ej14 = np.random.randint(1,25,(2,3,4))
print(array_ej14)
print("\n")
print(np.transpose(array_ej14))

[[[19 13 20  8]
  [ 6 13  9 13]
  [12 12 21 21]]

 [[23 15 20 22]
  [ 9  8  4  1]
  [ 5 19 20 18]]]


[[[19 23]
  [ 6  9]
  [12  5]]

 [[13 15]
  [13  8]
  [12 19]]

 [[20 20]
  [ 9  4]
  [21 20]]

 [[ 8 22]
  [13  1]
  [21 18]]]


 La función `np.transpose` intercambiar las dimensiones de un *array*. Toma como argumento un *array* y devuelve una nueva *array* con las dimensiones intercambiadas.
En el caso de un array bidimensional cambia las filas por columnas, en el caso de un array tridimensional cambia las matrices por columnas y deja fijas las filas. De esta forma se reorganizan los elementos del array y así cambian las posiciones y los índices de los valores.

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [149]:
array_ej15 = np.random.randint(1,25, (3,4,2))
print(array_ej15)
print("\n")
print("Resultado:")
print(np.swapaxes(array_ej15, 1,0))

[[[14 24]
  [ 8  6]
  [22 10]
  [14 12]]

 [[19  9]
  [19 10]
  [22 14]
  [23 19]]

 [[16  3]
  [ 1  6]
  [ 3 19]
  [11 11]]]


Resultado:
[[[14 24]
  [19  9]
  [16  3]]

 [[ 8  6]
  [19 10]
  [ 1  6]]

 [[22 10]
  [22 14]
  [ 3 19]]

 [[14 12]
  [23 19]
  [11 11]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [151]:
array_ej16 = np.random.randint(1,25, (3,2,4))
traspuesta = np.transpose(array_ej16)
cambio = np.swapaxes(traspuesta, 2,1)
print(array_ej16)
print("\n")
print("Resultado:")
print(cambio)

[[[12 17  6 21]
  [15 21  6  7]]

 [[ 6 16  3  7]
  [ 7 21 22 18]]

 [[10 17  3  2]
  [ 8  6 10 12]]]


Resultado:
[[[12 15]
  [ 6  7]
  [10  8]]

 [[17 21]
  [16 21]
  [17  6]]

 [[ 6  6]
  [ 3 22]
  [ 3 10]]

 [[21  7]
  [ 7 18]
  [ 2 12]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [167]:
array_ej17 = np.random.randint(-10,11, (3,4,5))
print(array_ej17)


[[[  2   0  -9  -7   2]
  [  0   3  -7   9  -1]
  [  2   8  -2   5  -4]
  [  3 -10   0   4  -8]]

 [[ -8   4   7   9 -10]
  [-10  -1   5  -9  -7]
  [  0   9  -9  -5   5]
  [  7   1  -8  -3  -6]]

 [[ -6  -6 -10  10  -9]
  [  9  -8  10   6  -1]
  [ -4   8  -4 -10   3]
  [ -2  -9  -7  -4   3]]]


In [171]:
array_vacio = np.empty((3,4,5), dtype='U5')

mediana = np.median(array_ej17)
max = np.max(array_ej17)
min = np.min(array_ej17)
print(f'Mediana: {mediana}')
print(f'Máximo: {max}')
print(f'Mínimo: {min}')

array_vacio[array_ej17 == mediana]= "M"
array_vacio[array_ej17 > mediana]= "X"
array_vacio[array_ej17 < mediana]= "Y"
array_vacio[array_ej17 == max]= "MAX"
array_vacio[array_ej17 == min]= "MIN"

array_vacio

Mediana: -1.0
Máximo: 10
Mínimo: -10


array([[['X', 'X', 'Y', 'Y', 'X'],
        ['X', 'X', 'Y', 'X', 'M'],
        ['X', 'X', 'Y', 'X', 'Y'],
        ['X', 'MIN', 'X', 'X', 'Y']],

       [['Y', 'X', 'X', 'X', 'MIN'],
        ['MIN', 'M', 'X', 'Y', 'Y'],
        ['X', 'X', 'Y', 'Y', 'X'],
        ['X', 'X', 'Y', 'Y', 'Y']],

       [['Y', 'Y', 'MIN', 'MAX', 'Y'],
        ['X', 'Y', 'MAX', 'X', 'M'],
        ['Y', 'X', 'Y', 'MIN', 'X'],
        ['Y', 'Y', 'Y', 'Y', 'X']]], dtype='<U5')

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [248]:
array_ej18 = np.random.randint(1,4, (3,3))
print(array_ej18)

array_ej18_true = np.array([[1,2,3],[3,1,1],[1,2,1]])
print(array_ej18_true)

[[2 2 1]
 [3 1 3]
 [1 3 3]]
[[1 2 3]
 [3 1 1]
 [1 2 1]]


In [249]:
def buscar():
    for fila in array_ej18:
        
        #Tomo el primer elemento y compruebo si hay algun otro en la matriz y ese otro está en la primera fila
        elem = fila[0]
        print("--------------------------------------")
        print(f'Elemento:{elem}')
        # Compruebo si ese elemento está en la matriz
        aux = np.where(array_ej18 == elem)
        print(np.where(array_ej18 == elem))

        # Si hay otro elemento igualen la matriz y esta en la primera fila continuo
        if 0 in aux[0]:
            # Tomo los indices de los 0 y compruebo que columnas son:
            indices_columnas= np.where(aux[0]==0)[0]
            print(f'Indices columnas: {indices_columnas}')
            print(len(indices_columnas))
            for ind in indices_columnas:
                print("-----------columnas---------")
                columna = aux[1][ind]
                print(f'Columna:{columna}')
                print(array_ej18[:,columna])

                i=0
                flag=0
                for elem_fila in fila:
                    print(f'Elemneto de la fila: {elem_fila}')
                    print(f'Elemento de la columna: {array_ej18[:,columna][i]}')
                    if elem_fila != array_ej18[:,columna][i]:
                        print()
                        flag=1
                        break
                    else:
                        i+=1
                if flag ==0:
                    return True

        else:
            print("Dentro")
            
    print("Final")
    return False
        
buscar()

--------------------------------------
Elemento:1
(array([0, 1, 1, 2, 2]), array([0, 1, 2, 0, 2]))
Indices columnas: [0]
1
-----------columnas---------
Columna:0
[1 3 1]
Elemneto de la fila: 1
Elemento de la columna: 1
Elemneto de la fila: 2
Elemento de la columna: 3

--------------------------------------
Elemento:3
(array([0, 1]), array([2, 0]))
Indices columnas: [0]
1
-----------columnas---------
Columna:2
[3 1 1]
Elemneto de la fila: 3
Elemento de la columna: 3
Elemneto de la fila: 1
Elemento de la columna: 1
Elemneto de la fila: 1
Elemento de la columna: 1


True